### ISSUE TITLE
sonar不通过质量阀，可以中断drone执行么？

### ISSUE THREAD

**Issue by tinyzh** [zongwei007/drone-sonarqube-scanner#2]

**Comment by zongwei007** [comment]
没关注过这个功能场景。
插件目前的工作方式很简单，就是生成配置然后调用 sonar-scanner。如果检测失败但 drone 仍继续运行，应该与 sonar-scanner 在检测完成后返回的退出码有关。这个行为应该是可以通过 sonar-scanner 的配置调整的。

随便搜了下，好像是设置 `sonar.qualitygate.wait=true` 。你可以试一下……

**Comment by tinyzh** [comment]
> 没关注过这个功能场景。
> 插件目前的工作方式很简单，就是生成配置然后调用 sonar-scanner。如果检测失败但 drone 仍继续运行，应该与 sonar-scanner 在检测完成后返回的退出码有关。这个行为应该是可以通过 sonar-scanner 的配置调整的。
> 
> 随便搜了下，好像是设置 `sonar.qualitygate.wait=true` 。你可以试一下……

这个参数可以用，感谢老哥
